const defaultOperators = {
  _eq: "Equals",
  _neq: "Doesn't equal",
  _lt: "Less than",
  _lte: "Less than or equal to",
  _gt: "Greater than",
  _gte: "Greater than or equal to",
  // "_in": "Is one of",
  // "_nin": "Is not one of",
  _null: "Is null",
  _nnull: "Isn't null",
  _contains: "Contains",
  _icontains: "Contains (case-insensitive)",
  _ncontains: "Doesn't contain",
  _starts_with: "Starts with",
  _istarts_with: "Starts with (case-insensitive)",
  _nstarts_with: "Doesn't start with",
  _nistarts_with: "Doesn't start with (case-insensitive)",
  _ends_with: "Ends with",
  _iends_with: "Ends with (case-insensitive)",
  _nends_with: "Doesn't end with",
  _niends_with: "Doesn't end with (case-insensitive)",
  _empty: "Is empty",
  _nempty: "Isn't empty",
}

export default defaultOperators;